import pandas as pd
import traceback
from promptflow import tool


@tool
def execute_python_code(code: str):
    """
    Executes LLM‑generated Python code against the Supply Chain dataset.
    The dataset is loaded from a fixed path and made available as `df`.
    The LLM must assign its answer to a variable named `result`.

    :param code: The Python code string generated by the LLM (may include ```python blocks).
    :return: A string representation of `result` or an error message.
    """
    file_path = "data/DataCoSupplyChainDataset.csv"

    # 1. Clean the code input (strip Markdown formatting)
    if not code:
        return "Error: No code provided by the LLM."

    if "```python" in code:
        # Corrected: split correctly and take the middle part
        parts = code.split("```python")
        code = parts[1].split("```")[0].strip()
    elif "```" in code:
        parts = code.split("```")
        code = parts[1].split("```").strip()

    try:
        # 2. Load the dataset (ISO‑8859‑1 is standard for this dataset)
        df = pd.read_csv(file_path, encoding="ISO-8859-1")

        # 3. Standardize column names
        # e.g., 'Delivery Status' -> 'Delivery_Status'
        #       'Days for shipping (real)' -> 'Days_for_shipping_real'
        df.columns = [
            col.replace(" ", "_")
               .replace("(", "")
               .replace(")", "")
               .replace("/", "_")
               .replace("-", "_")
            for col in df.columns
        ]

        # 4. Define execution environment
        # Pass df and pd into locals; initialize result to capture the LLM’s output.
        local_vars = {"df": df, "pd": pd, "result": None}

        # 5. Execute the code (with limited builtins for safety)
        exec(code, {"__builtins__": __builtins__}, local_vars)

        # 6. Extract the 'result' variable populated by the LLM
        execution_output = local_vars.get("result")

        if execution_output is None:
            return (
                "Success: Code executed, but no 'result' was assigned. "
                "Ensure your prompt tells the model to assign the answer to the 'result' variable."
            )

        # 7. Format output for the next node (Synthesis)
        if isinstance(execution_output, (pd.DataFrame, pd.Series)):
            # Use to_markdown() if available; fall back to to_string()
            try:
                return execution_output.to_markdown()
            except ImportError:
                return execution_output.to_string()

        return str(execution_output)

    except Exception as e:
        # Return error type and full traceback for debugging in Prompt Flow
        error_type = type(e).__name__
        return (
            f"Error during execution [{error_type}]: {str(e)}\n\n"
            f"Traceback:\n{traceback.format_exc()}"
        )
